// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbV7jhIxk8_duvHoNxkefu5uuhpeX7YXY',
    appId: '1:188954493304:web:8997f109889edddebd088d',
    messagingSenderId: '188954493304',
    projectId: 'test-43275',
    authDomain: 'test-43275.firebaseapp.com',
    storageBucket: 'test-43275.firebasestorage.app',
    measurementId: 'G-JHDZ77DV88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9yl0JhVyvKj23DATz3Y_wKIrPo50EwA',
    appId: '1:188954493304:android:4e8eab4e086a88d5bd088d',
    messagingSenderId: '188954493304',
    projectId: 'test-43275',
    storageBucket: 'test-43275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWeZqMd0G_T6O6L9DDVeeyPsY1zKkLAng',
    appId: '1:188954493304:ios:1b56a194f08c00ffbd088d',
    messagingSenderId: '188954493304',
    projectId: 'test-43275',
    storageBucket: 'test-43275.firebasestorage.app',
    androidClientId: '188954493304-pr3tdieleirhu07bnubhtuadt684jg7b.apps.googleusercontent.com',
    iosClientId: '188954493304-8kd7f861ml5j6sb155drd3o25jh3al24.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWeZqMd0G_T6O6L9DDVeeyPsY1zKkLAng',
    appId: '1:188954493304:ios:1b56a194f08c00ffbd088d',
    messagingSenderId: '188954493304',
    projectId: 'test-43275',
    storageBucket: 'test-43275.firebasestorage.app',
    androidClientId: '188954493304-pr3tdieleirhu07bnubhtuadt684jg7b.apps.googleusercontent.com',
    iosClientId: '188954493304-8kd7f861ml5j6sb155drd3o25jh3al24.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbV7jhIxk8_duvHoNxkefu5uuhpeX7YXY',
    appId: '1:188954493304:web:18990f554cb03f00bd088d',
    messagingSenderId: '188954493304',
    projectId: 'test-43275',
    authDomain: 'test-43275.firebaseapp.com',
    storageBucket: 'test-43275.firebasestorage.app',
    measurementId: 'G-27K2VG2M5F',
  );
}
